# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  #secret_key_base: c3f3ddd9d99151de6cf8aa1f5e8d58cfa80b4d4396b08b233881aa28d511812b59ca490ddd8224616ee1e152a2d9912c98855c5132a2c23872f1a0b291bd7fe7

test:
  secret_key_base: f02ce9c237d41b4b7a6ec423052abad0aea28249e74cfbb57d50728928fd0bcef868bccb607ce28542b9431172891959fa19ec6b9c38932fcf14f8b48421272a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
